# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\uni\уник\vkr\programm\code\interface\authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FullNameForm(object):
    def setupUi(self, FullNameForm):
        FullNameForm.setObjectName("FullNameForm")
        FullNameForm.resize(397, 122)
        self.gridLayout = QtWidgets.QGridLayout(FullNameForm)
        self.gridLayout.setObjectName("gridLayout")
        self.lastname_label = QtWidgets.QLabel(FullNameForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lastname_label.setFont(font)
        self.lastname_label.setObjectName("lastname_label")
        self.gridLayout.addWidget(self.lastname_label, 0, 0, 1, 1)
        self.lastname_line_edit = QtWidgets.QLineEdit(FullNameForm)
        self.lastname_line_edit.setObjectName("lastname_line_edit")
        self.gridLayout.addWidget(self.lastname_line_edit, 0, 1, 1, 1)
        self.firstname_label = QtWidgets.QLabel(FullNameForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstname_label.setFont(font)
        self.firstname_label.setObjectName("firstname_label")
        self.gridLayout.addWidget(self.firstname_label, 1, 0, 1, 1)
        self.firstname_line_edit = QtWidgets.QLineEdit(FullNameForm)
        self.firstname_line_edit.setObjectName("firstname_line_edit")
        self.gridLayout.addWidget(self.firstname_line_edit, 1, 1, 1, 1)
        self.patronymic_label = QtWidgets.QLabel(FullNameForm)
        self.patronymic_label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patronymic_label.setFont(font)
        self.patronymic_label.setObjectName("patronymic_label")
        self.gridLayout.addWidget(self.patronymic_label, 2, 0, 1, 1)
        self.patronymic_line_edit = QtWidgets.QLineEdit(FullNameForm)
        self.patronymic_line_edit.setObjectName("patronymic_line_edit")
        self.gridLayout.addWidget(self.patronymic_line_edit, 2, 1, 1, 1)
        self.dialog = QtWidgets.QDialogButtonBox(FullNameForm)
        self.dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialog.setObjectName("dialog")
        self.gridLayout.addWidget(self.dialog, 3, 1, 1, 1)

        self.retranslateUi(FullNameForm)
        QtCore.QMetaObject.connectSlotsByName(FullNameForm)

    def retranslateUi(self, FullNameForm):
        _translate = QtCore.QCoreApplication.translate
        FullNameForm.setWindowTitle(_translate("FullNameForm", "Form"))
        self.lastname_label.setText(_translate("FullNameForm", "Имя"))
        self.firstname_label.setText(_translate("FullNameForm", "Имя (домен)"))
        self.patronymic_label.setText(_translate("FullNameForm", "Пароль"))
